mdsp_guild_id = 764981968579461130

aman_id = 824167368737030174
votes_needed = 5

fripe_py_disendorcements = [
    "Thank you for forfeiting your spleen.",
    "Please use me instead :D",
    ">:(",
    "Bruh",
    "Suffer.",
    "I am going to eat your liver.",
    "You have been added to the hitlist",
    "That command was soooo 2022. Use mine instead.",
    "I am going to lose it",
    "please...",
    "I can't take this for much longer",
]
